name: Build APK with Buildozer
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Android SDK and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk wget unzip
        # Download and install Android SDK
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O /tmp/android-sdk.zip
        sudo unzip /tmp/android-sdk.zip -d /usr/local/android-sdk
        # Move the extracted command line tools to the proper location
        sudo mv /usr/local/android-sdk/cmdline-tools /usr/local/android-sdk/cmdline-tools/latest
        # Add android-sdk to the path
        echo "export ANDROID_HOME=/usr/local/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
        # Accept licenses and install necessary SDK components
        sdkmanager --licenses
        sdkmanager --update
        sdkmanager "build-tools;29.0.2" "platforms;android-29" "platform-tools" "tools"
        
    - name: Install Buildozer
      run: |
        sudo apt-get install -y python3-pip
        pip install --upgrade pip
        pip install buildozer

    - name: Build APK
      run: |
        cd your-project-directory
        buildozer android debug 
