name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install required system dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-11-jdk python3-pip libffi-dev libssl-dev liblzo2-dev libx11-dev zlib1g-dev
          pip install --upgrade pip setuptools

      # Install Buildozer
      - name: install buildozer
        run: |
          pip install buildozer
          buildozer init

      # Build the APK
      - name: Build APK
        run: |
          buildozer android debug

      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: bin/*.apk
