name: Build APK with Buildozer
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk
        sudo apt-get install -y android-sdk
        sudo apt-get install -y android-tools-adb
        sudo apt-get install -y android-tools-fastboot
        # Install AIDL and other dependencies
        sdkmanager "build-tools;29.0.2" "platforms;android-29" "platform-tools" "tools"
        sdkmanager --update

    - name: Install Buildozer
      run: |
        sudo apt-get install -y python3-pip
        pip install --upgrade pip
        pip install buildozer

    - name: Build APK
      run: |
        cd your-project-directory
        buildozer android debug 
